doctrine:
    dbal:
        default_connection: default
        connections:
            default:
                driver   : 'pdo_mysql'
                host     : '%env(DB_HOST)%'
                dbname   : '%env(DB_DATABASE)%'
                user     : '%env(DB_USERNAME)%'
                password : '%env(DB_PASSWORD)%'
                port     : '%env(DB_PORT)%'
                mapping_types:
                    enum: string

    orm:
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    Sakila\Entity:
                        type: xml
                        dir: '%kernel.project_dir%/config/doctrine'
                        is_bundle: false
                        prefix: Sakila\Entity
                        alias: Sakila
