doctrine:
    dbal:
        driver   : 'pdo_mysql'
        host     : '%env(DB_HOST)%'
        dbname   : '%env(DB_DATABASE)%'
        user     : '%env(DB_USERNAME)%'
        password : '%env(DB_PASSWORD)%'
        port     : '%env(DB_PORT)%'
