actors_show:
    path: /api/actors/{actorId}
    controller: Sakila\Http\Controllers\Api\ActorController::show
    methods: [GET]
    requirements:
        actorId: \d+

actors_list:
    path: /api/actors
    controller: Sakila\Http\Controllers\Api\ActorController::index
    methods: [GET]

actors_store:
    path: /api/actors
    controller: Sakila\Http\Controllers\Api\ActorController::store
    methods: [POST]

actors_update:
    path: /api/actors/{actorId}
    controller: Sakila\Http\Controllers\Api\ActorController::update
    methods: [PUT]

actors_destroy:
    path: /api/actors/{actorId}
    controller: Sakila\Http\Controllers\Api\ActorController::destroy
    methods: [DELETE]

addresses_show:
    path: /api/addresses/{addressId}
    controller: Sakila\Http\Controllers\Api\AddressController::show
    methods: [GET]
    requirements:
        addressId: \d+

addresses_list:
    path: /api/addresses
    controller: Sakila\Http\Controllers\Api\AddressController::index
    methods: [GET]

addresses_store:
    path: /api/addresses
    controller: Sakila\Http\Controllers\Api\AddressController::store
    methods: [POST]

addresses_update:
    path: /api/addresses/{addressId}
    controller: Sakila\Http\Controllers\Api\AddressController::update
    methods: [PUT]

addresses_destroy:
    path: /api/addresses/{addressId}
    controller: Sakila\Http\Controllers\Api\AddressController::destroy
    methods: [DELETE]

cities_show:
    path: /api/cities/{cityId}
    controller: Sakila\Http\Controllers\Api\CityController::show
    methods: [GET]
    requirements:
        cityId: \d+

cities_list:
    path: /api/cities
    controller: Sakila\Http\Controllers\Api\CityController::index
    methods: [GET]

cities_store:
    path: /api/cities
    controller: Sakila\Http\Controllers\Api\CityController::store
    methods: [POST]

cities_update:
    path: /api/cities/{cityId}
    controller: Sakila\Http\Controllers\Api\CityController::update
    methods: [PUT]

cities_destroy:
    path: /api/cities/{cityId}
    controller: Sakila\Http\Controllers\Api\CityController::destroy
    methods: [DELETE]

categories_show:
    path: /api/categories/{categoryId}
    controller: Sakila\Http\Controllers\Api\CategoryController::show
    methods: [GET]
    requirements:
        categoryId: \d+

categories_list:
    path: /api/categories
    controller: Sakila\Http\Controllers\Api\CategoryController::index
    methods: [GET]

categories_store:
    path: /api/categories
    controller: Sakila\Http\Controllers\Api\CategoryController::store
    methods: [POST]

categories_update:
    path: /api/categories/{categoryId}
    controller: Sakila\Http\Controllers\Api\CategoryController::update
    methods: [PUT]

categories_destroy:
    path: /api/categories/{categoryId}
    controller: Sakila\Http\Controllers\Api\CategoryController::destroy
    methods: [DELETE]
