actors_show:
    path: /api/actors/{actorId}
    controller: Sakila\Http\Controllers\Api\ActorController::show
    methods: [GET]
    requirements:
        actorId: \d+

actors_list:
    path: /api/actors
    controller: Sakila\Http\Controllers\Api\ActorController::index
    methods: [GET]

actors_store:
    path: /api/actors
    controller: Sakila\Http\Controllers\Api\ActorController::store
    methods: [POST]

actors_update:
    path: /api/actors/{actorId}
    controller: Sakila\Http\Controllers\Api\ActorController::update
    methods: [PUT]

actors_destroy:
    path: /api/actors/{actorId}
    controller: Sakila\Http\Controllers\Api\ActorController::destroy
    methods: [DELETE]

addresses_show:
    path: /api/addresses/{addressId}
    controller: Sakila\Http\Controllers\Api\AddressController::show
    methods: [GET]
    requirements:
        addressId: \d+

addresses_list:
    path: /api/addresses
    controller: Sakila\Http\Controllers\Api\AddressController::index
    methods: [GET]

addresses_store:
    path: /api/addresses
    controller: Sakila\Http\Controllers\Api\AddressController::store
    methods: [POST]

addresses_update:
    path: /api/addresses/{addressId}
    controller: Sakila\Http\Controllers\Api\AddressController::update
    methods: [PUT]

addresses_destroy:
    path: /api/addresses/{addressId}
    controller: Sakila\Http\Controllers\Api\AddressController::destroy
    methods: [DELETE]

cities_show:
    path: /api/cities/{cityId}
    controller: Sakila\Http\Controllers\Api\CityController::show
    methods: [GET]
    requirements:
        cityId: \d+

cities_list:
    path: /api/cities
    controller: Sakila\Http\Controllers\Api\CityController::index
    methods: [GET]

cities_store:
    path: /api/cities
    controller: Sakila\Http\Controllers\Api\CityController::store
    methods: [POST]

cities_update:
    path: /api/cities/{cityId}
    controller: Sakila\Http\Controllers\Api\CityController::update
    methods: [PUT]

cities_destroy:
    path: /api/cities/{cityId}
    controller: Sakila\Http\Controllers\Api\CityController::destroy
    methods: [DELETE]

categories_show:
    path: /api/categories/{categoryId}
    controller: Sakila\Http\Controllers\Api\CategoryController::show
    methods: [GET]
    requirements:
        categoryId: \d+

categories_list:
    path: /api/categories
    controller: Sakila\Http\Controllers\Api\CategoryController::index
    methods: [GET]

categories_store:
    path: /api/categories
    controller: Sakila\Http\Controllers\Api\CategoryController::store
    methods: [POST]

categories_update:
    path: /api/categories/{categoryId}
    controller: Sakila\Http\Controllers\Api\CategoryController::update
    methods: [PUT]

categories_destroy:
    path: /api/categories/{categoryId}
    controller: Sakila\Http\Controllers\Api\CategoryController::destroy
    methods: [DELETE]


countries_show:
    path: /api/countries/{countryId}
    controller: Sakila\Http\Controllers\Api\CountryController::show
    methods: [GET]
    requirements:
        countryId: \d+

countries_list:
    path: /api/countries
    controller: Sakila\Http\Controllers\Api\CountryController::index
    methods: [GET]

countries_store:
    path: /api/countries
    controller: Sakila\Http\Controllers\Api\CountryController::store
    methods: [POST]

countries_update:
    path: /api/countries/{countryId}
    controller: Sakila\Http\Controllers\Api\CountryController::update
    methods: [PUT]

countries_destroy:
    path: /api/countries/{countryId}
    controller: Sakila\Http\Controllers\Api\CountryController::destroy
    methods: [DELETE]

customers_show:
    path: /api/customers/{customerId}
    controller: Sakila\Http\Controllers\Api\CustomerController::show
    methods: [GET]
    requirements:
        customerId: \d+

customers_list:
    path: /api/customers
    controller: Sakila\Http\Controllers\Api\CustomerController::index
    methods: [GET]

customers_store:
    path: /api/customers
    controller: Sakila\Http\Controllers\Api\CustomerController::store
    methods: [POST]

customers_update:
    path: /api/customers/{customerId}
    controller: Sakila\Http\Controllers\Api\CustomerController::update
    methods: [PUT]

customers_destroy:
    path: /api/customers/{customerId}
    controller: Sakila\Http\Controllers\Api\CustomerController::destroy
    methods: [DELETE]

films_show:
    path: /api/films/{filmId}
    controller: Sakila\Http\Controllers\Api\FilmController::show
    methods: [GET]
    requirements:
        filmId: \d+

films_list:
    path: /api/films
    controller: Sakila\Http\Controllers\Api\FilmController::index
    methods: [GET]

films_store:
    path: /api/films
    controller: Sakila\Http\Controllers\Api\FilmController::store
    methods: [POST]

films_update:
    path: /api/films/{filmId}
    controller: Sakila\Http\Controllers\Api\FilmController::update
    methods: [PUT]

films_destroy:
    path: /api/films/{filmId}
    controller: Sakila\Http\Controllers\Api\FilmController::destroy
    methods: [DELETE]

inventory_show:
    path: /api/inventory/{inventoryId}
    controller: Sakila\Http\Controllers\Api\InventoryController::show
    methods: [GET]
    requirements:
        inventoryId: \d+

inventory_list:
    path: /api/inventory
    controller: Sakila\Http\Controllers\Api\InventoryController::index
    methods: [GET]

inventory_store:
    path: /api/inventory
    controller: Sakila\Http\Controllers\Api\InventoryController::store
    methods: [POST]

inventory_update:
    path: /api/inventory/{inventoryId}
    controller: Sakila\Http\Controllers\Api\InventoryController::update
    methods: [PUT]

inventory_destroy:
    path: /api/inventory/{inventoryId}
    controller: Sakila\Http\Controllers\Api\InventoryController::destroy
    methods: [DELETE]

languages_show:
    path: /api/languages/{languageId}
    controller: Sakila\Http\Controllers\Api\LanguageController::show
    methods: [GET]
    requirements:
        languageId: \d+

languages_list:
    path: /api/languages
    controller: Sakila\Http\Controllers\Api\LanguageController::index
    methods: [GET]

languages_store:
    path: /api/languages
    controller: Sakila\Http\Controllers\Api\LanguageController::store
    methods: [POST]

languages_update:
    path: /api/languages/{languageId}
    controller: Sakila\Http\Controllers\Api\LanguageController::update
    methods: [PUT]

languages_destroy:
    path: /api/languages/{languageId}
    controller: Sakila\Http\Controllers\Api\LanguageController::destroy
    methods: [DELETE]

payments_show:
    path: /api/payments/{paymentId}
    controller: Sakila\Http\Controllers\Api\PaymentController::show
    methods: [GET]
    requirements:
        paymentId: \d+

payments_list:
    path: /api/payments
    controller: Sakila\Http\Controllers\Api\PaymentController::index
    methods: [GET]

payments_store:
    path: /api/payments
    controller: Sakila\Http\Controllers\Api\PaymentController::store
    methods: [POST]

payments_update:
    path: /api/payments/{paymentId}
    controller: Sakila\Http\Controllers\Api\PaymentController::update
    methods: [PUT]

payments_destroy:
    path: /api/payments/{paymentId}
    controller: Sakila\Http\Controllers\Api\PaymentController::destroy
    methods: [DELETE]

rentals_show:
    path: /api/rentals/{rentalId}
    controller: Sakila\Http\Controllers\Api\RentalController::show
    methods: [GET]
    requirements:
        rentalId: \d+

rentals_list:
    path: /api/rentals
    controller: Sakila\Http\Controllers\Api\RentalController::index
    methods: [GET]

rentals_store:
    path: /api/rentals
    controller: Sakila\Http\Controllers\Api\RentalController::store
    methods: [POST]

rentals_update:
    path: /api/rentals/{rentalId}
    controller: Sakila\Http\Controllers\Api\RentalController::update
    methods: [PUT]

rentals_destroy:
    path: /api/rentals/{rentalId}
    controller: Sakila\Http\Controllers\Api\RentalController::destroy
    methods: [DELETE]

stores_show:
    path: /api/stores/{storeId}
    controller: Sakila\Http\Controllers\Api\StoreController::show
    methods: [GET]
    requirements:
        storeId: \d+

stores_list:
    path: /api/stores
    controller: Sakila\Http\Controllers\Api\StoreController::index
    methods: [GET]

stores_store:
    path: /api/stores
    controller: Sakila\Http\Controllers\Api\StoreController::store
    methods: [POST]

stores_update:
    path: /api/stores/{storeId}
    controller: Sakila\Http\Controllers\Api\StoreController::update
    methods: [PUT]

stores_destroy:
    path: /api/stores/{storeId}
    controller: Sakila\Http\Controllers\Api\StoreController::destroy
    methods: [DELETE]
