# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false       # Allows optimizing the container by removing unused services; this also means
                            # fetching services directly from the container via $container->get() won't work.
                            # The best practice is to be explicit about your dependencies anyway.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    Sakila\:
        resource: '../app/*'
        exclude: '../app/{Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    Sakila\Http\Controllers\Api\:
        resource: '../app/Http/Controllers/Api'
        tags: ['controller.service_arguments']

    Sakila\EventListener\RequestListener:
        tags:
            - { name: kernel.event_listener, event: kernel.request }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
    League\Fractal\Manager: ~

    League\Tactician\CommandBus:
        factory: ['Sakila\Factories\TacticianCommandBusFactory', create]

    Sakila\Command\Bus\CommandBusInterface: '@Sakila\Command\Bus\TacticianCommandBusAdapter'

    Sakila\Transformer\TransformerInterface: '@Sakila\Transformer\FractalTransformerAdapter'

    Sakila\Entity\Builder: ~
    Sakila\Entity\Factory: ~

    Sakila\Repository\Database\Table\SimpleNameResolver: ~
    Sakila\Repository\Database\Table\NameResolverInterface: '@Sakila\Repository\Database\Table\SimpleNameResolver'

    Sakila\Repository\Database\Doctrine\Connection: ~
    Sakila\Repository\Database\ConnectionInterface: '@Sakila\Repository\Database\Doctrine\Connection'

    Sakila\Entity\FactoryAdapter: ~
    Sakila\Entity\FactoryInterface: '@Sakila\Entity\FactoryAdapter'


    Sakila\Domain\Actor\Repository\Database\ActorRepository: ~
    Sakila\Domain\Actor\Repository\ActorRepositoryInterface: '@Sakila\Domain\Actor\Repository\Database\ActorRepository'

    Sakila\Transformer\ActorTransformer: ~
    Sakila\Domain\Actor\Entity\Transformer\ActorTransformerInterface:
        alias: Sakila\Transformer\ActorTransformer
        public: true

    Sakila\Domain\Actor\Entity\Mapper\ActorMapper: ~
    Sakila\Validators\ActorValidator: ~
    Sakila\Domain\Actor\Validator\ActorValidatorInterface: '@Sakila\Validators\ActorValidator'

    Sakila\Domain\Actor\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Actor/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Actor/Service/Request'
        public: true


    Sakila\Domain\Address\Repository\Database\AddressRepository: ~
    Sakila\Domain\Address\Repository\AddressRepositoryInterface: '@Sakila\Domain\Address\Repository\Database\AddressRepository'

    Sakila\Transformer\AddressTransformer: ~
    Sakila\Domain\Address\Entity\Transformer\AddressTransformerInterface:
        alias: Sakila\Transformer\AddressTransformer
        public: true

    Sakila\Domain\Address\Entity\Mapper\AddressMapper: ~
    Sakila\Validators\AddressValidator: ~
    Sakila\Domain\Address\Validator\AddressValidatorInterface: '@Sakila\Validators\AddressValidator'

    Sakila\Domain\Address\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Address/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Address/Service/Request'
        public: true


    Sakila\Domain\City\Repository\Database\CityRepository: ~
    Sakila\Domain\City\Repository\CityRepositoryInterface: '@Sakila\Domain\City\Repository\Database\CityRepository'

    Sakila\Transformer\CityTransformer: ~
    Sakila\Domain\City\Entity\Transformer\CityTransformerInterface:
        alias: Sakila\Transformer\CityTransformer
        public: true

    Sakila\Domain\City\Entity\Mapper\CityMapper: ~
    Sakila\Validators\CityValidator: ~
    Sakila\Domain\City\Validator\CityValidatorInterface: '@Sakila\Validators\CityValidator'

    Sakila\Domain\City\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/City/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/City/Service/Request'
        public: true


    Sakila\Domain\Category\Repository\Database\CategoryRepository: ~
    Sakila\Domain\Category\Repository\CategoryRepositoryInterface: '@Sakila\Domain\Category\Repository\Database\CategoryRepository'

    Sakila\Transformer\CategoryTransformer: ~
    Sakila\Domain\Category\Entity\Transformer\CategoryTransformerInterface:
        alias: Sakila\Transformer\CategoryTransformer
        public: true

    Sakila\Domain\Category\Entity\Mapper\CategoryMapper: ~
    Sakila\Validators\CategoryValidator: ~
    Sakila\Domain\Category\Validator\CategoryValidatorInterface: '@Sakila\Validators\CategoryValidator'

    Sakila\Domain\Category\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Category/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Category/Service/Request'
        public: true


    Sakila\Domain\Country\Repository\Database\CountryRepository: ~
    Sakila\Domain\Country\Repository\CountryRepositoryInterface: '@Sakila\Domain\Country\Repository\Database\CountryRepository'

    Sakila\Transformer\CountryTransformer: ~
    Sakila\Domain\Country\Entity\Transformer\CountryTransformerInterface:
        alias: Sakila\Transformer\CountryTransformer
        public: true

    Sakila\Domain\Country\Entity\Mapper\CountryMapper: ~
    Sakila\Validators\CountryValidator: ~
    Sakila\Domain\Country\Validator\CountryValidatorInterface: '@Sakila\Validators\CountryValidator'

    Sakila\Domain\Country\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Country/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Country/Service/Request'
        public: true


    Sakila\Domain\Customer\Repository\Database\CustomerRepository: ~
    Sakila\Domain\Customer\Repository\CustomerRepositoryInterface: '@Sakila\Domain\Customer\Repository\Database\CustomerRepository'

    Sakila\Transformer\CustomerTransformer: ~
    Sakila\Domain\Customer\Entity\Transformer\CustomerTransformerInterface:
        alias: Sakila\Transformer\CustomerTransformer
        public: true

    Sakila\Domain\Customer\Entity\Mapper\CustomerMapper: ~
    Sakila\Validators\CustomerValidator: ~
    Sakila\Domain\Customer\Validator\CustomerValidatorInterface: '@Sakila\Validators\CustomerValidator'

    Sakila\Domain\Customer\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Customer/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Customer/Service/Request'
        public: true


    Sakila\Domain\Film\Repository\Database\FilmRepository: ~
    Sakila\Domain\Film\Repository\FilmRepositoryInterface: '@Sakila\Domain\Film\Repository\Database\FilmRepository'

    Sakila\Transformer\FilmTransformer: ~
    Sakila\Domain\Film\Entity\Transformer\FilmTransformerInterface:
        alias: Sakila\Transformer\FilmTransformer
        public: true

    Sakila\Domain\Film\Entity\Mapper\FilmMapper: ~
    Sakila\Validators\FilmValidator: ~
    Sakila\Domain\Film\Validator\FilmValidatorInterface: '@Sakila\Validators\FilmValidator'

    Sakila\Domain\Film\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Film/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Film/Service/Request'
        public: true

    Sakila\Domain\Inventory\Repository\Database\InventoryRepository: ~
    Sakila\Domain\Inventory\Repository\InventoryRepositoryInterface: '@Sakila\Domain\Inventory\Repository\Database\InventoryRepository'

    Sakila\Transformer\InventoryTransformer: ~
    Sakila\Domain\Inventory\Entity\Transformer\InventoryTransformerInterface:
        alias: Sakila\Transformer\InventoryTransformer
        public: true

    Sakila\Domain\Inventory\Entity\Mapper\InventoryMapper: ~
    Sakila\Validators\InventoryValidator: ~
    Sakila\Domain\Inventory\Validator\InventoryValidatorInterface: '@Sakila\Validators\InventoryValidator'

    Sakila\Domain\Inventory\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Inventory/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Inventory/Service/Request'
        public: true

    Sakila\Domain\Language\Repository\Database\LanguageRepository: ~
    Sakila\Domain\Language\Repository\LanguageRepositoryInterface: '@Sakila\Domain\Language\Repository\Database\LanguageRepository'

    Sakila\Transformer\LanguageTransformer: ~
    Sakila\Domain\Language\Entity\Transformer\LanguageTransformerInterface:
        alias: Sakila\Transformer\LanguageTransformer
        public: true

    Sakila\Domain\Language\Entity\Mapper\LanguageMapper: ~
    Sakila\Validators\LanguageValidator: ~
    Sakila\Domain\Language\Validator\LanguageValidatorInterface: '@Sakila\Validators\LanguageValidator'

    Sakila\Domain\Language\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Language/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Language/Service/Request'
        public: true

    Sakila\Domain\Payment\Repository\Database\PaymentRepository: ~
    Sakila\Domain\Payment\Repository\PaymentRepositoryInterface: '@Sakila\Domain\Payment\Repository\Database\PaymentRepository'

    Sakila\Transformer\PaymentTransformer: ~
    Sakila\Domain\Payment\Entity\Transformer\PaymentTransformerInterface:
        alias: Sakila\Transformer\PaymentTransformer
        public: true

    Sakila\Domain\Payment\Entity\Mapper\PaymentMapper: ~
    Sakila\Validators\PaymentValidator: ~
    Sakila\Domain\Payment\Validator\PaymentValidatorInterface: '@Sakila\Validators\PaymentValidator'

    Sakila\Domain\Payment\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Payment/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Payment/Service/Request'
        public: true

    Sakila\Domain\Rental\Repository\Database\RentalRepository: ~
    Sakila\Domain\Rental\Repository\RentalRepositoryInterface: '@Sakila\Domain\Rental\Repository\Database\RentalRepository'

    Sakila\Transformer\RentalTransformer: ~
    Sakila\Domain\Rental\Entity\Transformer\RentalTransformerInterface:
        alias: Sakila\Transformer\RentalTransformer
        public: true

    Sakila\Domain\Rental\Entity\Mapper\RentalMapper: ~
    Sakila\Validators\RentalValidator: ~
    Sakila\Domain\Rental\Validator\RentalValidatorInterface: '@Sakila\Validators\RentalValidator'

    Sakila\Domain\Rental\Service\:
        resource: '../vendor/piobuddev/sakila/src/Domain/Rental/Service/*'
        exclude: '../vendor/piobuddev/sakila/src/Domain/Rental/Service/Request'
        public: true
